import type { ToqySite } from "./types";
import { createSiteFromSegmentTemplate } from "./segmentTemplates";

export const mockSites: ToqySite[] = [
  createSiteFromSegmentTemplate("barbearia", {
    id: "demo-barbearia",
    slug: "barbearia-andrian",
    status: "active",
    profile: {
      name: "Espaco Andrian",
      title: "Barbearia & Estetica",
      description: "Barbearia & Estetica. Agende seu horario, acesse o Wi-Fi ou pague no Pix com facilidade.",
      location: "R. Santo Antonio, 170 Centro, Vargem Grande do Sul - SP",
      logoUrl: "/images/logo.jpeg",
      profileImageUrl: "/images/logo.jpeg",
      backgroundImageUrl: "",
      logoSize: "large",
      logoShape: "circle",
    },
    theme: {
      mode: "dark",
      backgroundType: "gradient",
      background: "#050a12",
      gradientFrom: "#050a12",
      gradientTo: "#152033",
      card: "rgba(15, 23, 42, 0.86)",
      text: "#f8fafc",
      muted: "#cbd5e1",
      primary: "#31c4a8",
      secondary: "#203044",
      accent: "#e8c878",
      buttonFill: "glass",
      buttonStyle: "full",
      buttonRadius: "rounded",
      useBackgroundOverlay: true,
    },
    contact: {
      whatsapp: "5511999999999",
      phone: "5511999999999",
      whatsappMessage: "Ola! Vim pelo Toqy e gostaria de agendar um horario.",
      instagram: "https://instagram.com/barbeariaandrian",
      email: "",
      website: "",
    },
    links: {
      googleMapsUrl: "https://maps.google.com",
      googleReviewUrl: "https://google.com",
      bookingUrl: "https://barbeariaandrian.booksy.com",
      menuUrl: "",
    },
    pix: { enabled: true, key: "11999999999", receiver: "Espaco Andrian", bank: "Pix", quickAmounts: [35, 55, 80], allowCustomAmount: true, whatsappProofNumber: "5511999999999" },
    wifi: { enabled: true, ssid: "Barbearia Andrian", password: "recorecobolao", encryption: "WPA" },
    catalogLayout: "stack",
    catalog: [
      { id: "corte", name: "Corte Masculino", description: "Corte de cabelo impecavel e finalizado do seu jeito.", price: "R$ 40,00", imageUrl: "/images/corte_cabelo.jpg", imageLayout: "horizontal", category: "Cortes", enabled: true, actionLabel: "Agendar Horario" },
      { id: "barba", name: "Barba", description: "Modelagem, acabamento e toalha quente para um visual alinhado.", price: "R$ 35,00", imageUrl: "/images/barba_terapia.jpg", imageLayout: "horizontal", category: "Barba", enabled: true, actionLabel: "Agendar Horario" },
      { id: "combo", name: "Corte + Barba", description: "Combo completo com corte, barba e finalizacao premium.", price: "R$ 70,00", imageUrl: "/images/combo_corte_barba.jpg", imageLayout: "horizontal", category: "Combos", enabled: true, actionLabel: "Agendar Horario" },
      { id: "sobrancelha", name: "Sobrancelha", description: "Aparo e design masculino para valorizar o rosto.", price: "R$ 20,00", imageLayout: "horizontal", category: "Cuidados", enabled: true, actionLabel: "Agendar Horario" },
      { id: "limpeza", name: "Limpeza de Pele", description: "Cuidado facial para renovar a pele e melhorar o acabamento.", price: "R$ 65,00", imageUrl: "/images/limpeza_pele.jpg", imageLayout: "horizontal", category: "Cuidados", enabled: true, actionLabel: "Agendar Horario" },
      { id: "escalda", name: "Escalda Pes", description: "Tratamento relaxante com ervas, oleos essenciais e massagem.", price: "R$ 75,00", imageUrl: "/images/escalda_pes.jpg", imageLayout: "horizontal", category: "Relaxamento", enabled: true, actionLabel: "Agendar Horario" },
      { id: "capilar", name: "Tratamento Capilar", description: "Tratamento para fortalecer, hidratar e cuidar dos fios.", price: "R$ 60,00", imageUrl: "/images/terapia_capilar.jpg", imageLayout: "horizontal", category: "Cuidados", enabled: true, actionLabel: "Agendar Horario" },
      { id: "premium", name: "Combo Premium", description: "Corte, barba, sobrancelha e cuidado completo em uma experiencia unica.", price: "R$ 110,00", imageUrl: "/images/combo_corte_barba.jpg", imageLayout: "horizontal", category: "Combos", enabled: true, actionLabel: "Agendar Horario" },
      { id: "noivo", name: "Dia do Noivo", description: "Preparacao completa para um dia especial, com horario reservado.", price: "Sob consulta", imageUrl: "/images/corte_cabelo.jpg", imageLayout: "horizontal", category: "Eventos", enabled: true, actionLabel: "Chamar no WhatsApp" },
    ],
    editKey: "8392-1147",
  }),
  createSiteFromSegmentTemplate("pastelaria", {
    id: "demo-pastel",
    slug: "pastel-da-praca",
    status: "active",
    profile: { name: "Pastel da Praca", title: "Pastelaria e lanches", description: "Pasteis crocantes, combos e atendimento rapido pelo WhatsApp.", location: "Centro, Indaiatuba", logoSize: "medium", logoShape: "rounded" },
    contact: { whatsapp: "5511988888888", phone: "5511988888888", whatsappMessage: "Ola! Quero fazer um pedido pelo Toqy.", instagram: "https://instagram.com/pasteldapraca" },
    links: { googleMapsUrl: "https://maps.google.com", googleReviewUrl: "https://google.com", menuUrl: "https://example.com/cardapio" },
    pix: { enabled: true, key: "pix@pasteldapraca.com", receiver: "Pastel da Praca", quickAmounts: [12, 24, 49], allowCustomAmount: true, whatsappProofNumber: "5511988888888" },
    editKey: "2222-3333",
  }),
  createSiteFromSegmentTemplate("assistencia_tecnica", {
    id: "demo-mycell",
    slug: "my-cell",
    status: "active",
    profile: { name: "M.Y Cell", title: "Assistencia tecnica", description: "Conserto de celulares, acessorios, peliculas e diagnosticos rapidos.", location: "Indaiatuba, SP", logoSize: "medium", logoShape: "rounded" },
    contact: { whatsapp: "5511977777777", phone: "5511977777777", whatsappMessage: "Ola! Quero orcamento pelo Toqy.", instagram: "https://instagram.com/mycell" },
    links: { googleMapsUrl: "https://maps.google.com", googleReviewUrl: "https://google.com" },
    pix: { enabled: true, key: "11977777777", receiver: "M.Y Cell", quickAmounts: [25, 50, 100], allowCustomAmount: true, whatsappProofNumber: "5511977777777" },
    editKey: "4444-5555",
  }),
  createSiteFromSegmentTemplate("salao", { id: "demo-salao", slug: "salao-demo", status: "active", profile: { name: "Studio Bella", title: "Salao de beleza", description: "Beleza, cuidados e agendamentos em uma pagina simples.", location: "Indaiatuba, SP", logoSize: "medium", logoShape: "circle" }, editKey: "6666-7777" }),
  createSiteFromSegmentTemplate("clinica", { id: "demo-clinica", slug: "clinica-demo", status: "active", profile: { name: "Clinica Vida", title: "Saude e bem-estar", description: "Agendamentos, localizacao e servicos em uma pagina profissional.", location: "Indaiatuba, SP", logoSize: "medium", logoShape: "rounded" }, editKey: "8888-9999" }),
  createSiteFromSegmentTemplate("loja", { id: "demo-loja", slug: "loja-demo", status: "active", profile: { name: "Loja Demo", title: "Vitrine digital", description: "Produtos, atendimento e pagamento em poucos toques.", location: "Indaiatuba, SP", logoSize: "medium", logoShape: "rounded" }, editKey: "1111-2222" }),
];

export function getMockSiteBySlug(slug: string) {
  return mockSites.find((site) => site.slug === slug);
}
